import Head from 'next/head'

export default function layout({title ,children}) {
    return (
    <div>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon1.png" />
        </Head>
        <div className=" container mx-auto py-2 sm:py-6 sm:px-4">
            {children}
        </div>
    </div>

    )
}
