import Head from 'next/head'

export default function layout({title ,children}) {
    return (
    <div>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon1.png" />
        </Head>
        <div className="container py-2 mx-auto sm:py-6 sm:px-4">
            {children}
        </div>
        <footer className="fixed bottom-0 w-full p-2 bg-black ">
            <div className="flex items-center justify-center text-xs text-white">
                Challenge by <a className="px-1 text-teal-500 border-b-2 border-teal-500" href="https://www.frontendmentor.io/">Frontend Mentor.</a>
                Coded by <a className="pl-1 text-teal-500 border-b-2 border-teal-500" href="https://portfolio-v2-self.vercel.app/"> SafwanAzman.</a>
            </div>
        </footer>
    </div>

    )
}
