import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex justify-center bg-blue-500 items-center">
          <h1 className="text-white text-center text-5xl">FIRST</h1>
      </div>
    </div>
  )
}
